swagger: '2.0'
info:
  version: '1.0'
  title: Tiny Url
  description: 'Generating tiny url for long url'
  contact: {}
host: localhost:3000
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /ping:
    get:
      description: 'Returns ok if Api server is running'
      summary: check if server is running
      tags:
      - Misc
      operationId: OK
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: 'Server is running and mongodb connected'
          headers: {}
        500:
          description: 'Mongodb is not connected'
  /url/create:
    post:
      description: 'Add a long url in database and returns the short url'
      summary: Add a short url
      tags:
      - Misc
      operationId: addshorturls
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/addshorturl'
      responses:
        200:
          description: 'short url added successfully'
        500: 
          description: 'Internal Error like mongodb or any internal error'
  /urlCount/:fromDate/:toDate:
    get:
      description: 'get number of short urls creatd fromDate to todate rnge'
      summary: Get short url counts 
      tags:
      - Misc
      operationId: countshorturl
      deprecated: false
      produces:
      - application/json
      responses:
        200:
          description: 'count returned successfully'
        406: 
          description: 'fromdate and todate is required'
        500: 
          description: 'Internal Error like mongodb or any internal error'
  /:shortUrl:
    get:
      description: 'get long url for provided short url'
      summary: Get long url
      tags:
      - Misc
      operationId: getlongurl
      deprecated: false
      produces:
      - application/json
      responses:
        200:
          description: 'return long url if found'
          headers: {}
        406: 
          description: 'short url is not provided'
        500: 
          description: 'Internal Error like mongodb or any internal error'
definitions:
  addshorturl:
    title: addShortUrlRequest
    example:
      url: https://editor.swagger.io/
    type: object
    properties:
      url:
        type: string
    required:
    - url
tags:
- name: Misc
  description: ''